<template>
  <div>
    <h2 class="subtitle">Recomendaciones para las empresas</h2>
    <p><span class="subitem">Formule una política corporativa clara y estricta y ancle la gestión empresarial responsable en los procesos centrales.</span> Para llevar a cabo negocios sostenibles en un entorno desafiante como Latinoamérica, se necesita una política corporativa clara y estricta. La gerencia de la empresa debe dejar en claro que solo tolera y recompensa el comportamiento responsable, incluso si la empresa sufre desventajas económicas a corto plazo. Además, las empresas debieran pensar y alinear todos los procesos comerciales con los principios de gestión empresarial responsable. Al hacerlo, pueden seguir los ejemplos exitosos de empresas que han reconocido y utilizan la gestión empresarial responsable como un elemento diferenciador, impulsor de la innovación y la productividad.</p>
    <p><span class="subitem">Asegurar una gestión empresarial responsable en la cadena de valor.</span> Además de garantizar la conducción responsable de las actividades corporativas, las empresas también deben velar por que la gestión responsable se viva a lo largo de la cadena de valor, incluidos los subcontratistas. Para ello, las empresas deben aprovechar su posición en sus respectivas esferas de influencia y entablar un diálogo abierto y transparente con sus contrapartes para trabajar juntos sobre cómo utilizar la gestión empresarial responsable como un elemento diferenciador, innovador e impulsor de la productividad.</p>
    <p><span class="subitem">Involucrarse proactivamente en la difusión de los principios de la gestión empresarial responsable.</span> En América Latina, la gestión empresarial responsable sigue siendo un concepto relativamente poco común. A nivel internacional, están aumentando las expectativas de los grupos de interés frente a las empresas, para que estas sigan un comportamiento responsable a nivel mundial y a lo largo de toda la cadena de valor. Si en algunos países existen estándares legales insuficientes para cumplir con las normas ambientales y sociales, o si su implementación no es supervisada suficientemente por las instituciones estatales, esto puede generar desventajas competitivas para las empresas respecto a países con mayores demandas. Para garantizar la igualdad de condiciones, las empresas (multinacionales) deben trabajar proactivamente dentro de su esfera de influencia para difundir los principios de la gestión empresarial responsable. Esto puede realizarse, por ejemplo, en el marco de acciones colectivas.</p>
    <h2 class="subtitle">Recomendaciones para los actores estatales</h2>
    <p><span class="subitem">Transferir buenas prácticas del sector privado al sector público.</span> En los últimos años, un gran número de empresas privadas han hecho todo lo posible para prevenir, detectar y, de ser necesario, penalizar internamente las acciones irresponsables. Numerosas herramientas desarrolladas en el sector privado para garantizar el manejo responsable en las organizaciones (Código de Conducta, Oficinas de Defensoría, Hotlines, etc.) pueden ser adaptadas para el sector público. Es preciso aplicar los tres pasos, “prevenir – descubrir – sancionar”, más a menudo también en instituciones y empresas estatales.</p>
    <p><span class="subitem">Aplicar el concepto pilar de los Principios Rectores de la ONU a otros temas.</span> Los Principios Rectores de las Naciones Unidas para la Economía y los Derechos Humanos brindan un marco referencial importante que puede aplicarse en otras áreas de la gestión empresarial responsable. Por un lado, los Principios Rectores definen el deber de los estados de proteger los derechos humanos contra las amenazas de los actores del sector privado. Por otro lado, enfatizan el deber de las empresas de respetar los derechos humanos. Además, consagran un derecho a reparación en caso de violaciones de los derechos humanos cometidas por actores del sector privado.</p>
    <p><span class="subitem">Crear incentivos para implementar una gestión empresarial responsable.</span> La implementación de la gestión empresarial responsable es principalmente responsabilidad de las empresas. Esto aplica en particular si las compañías se comprometen adicional y voluntariamente con preocupaciones sociales y / o ecológicas, más allá de las disposiciones legales existentes. El deber de las instituciones estatales es contar con herramientas efectivas de control y sanción para detectar y enjuiciar el comportamiento ilícito. Además, el estado debiera establecer incentivos positivos para que los actores del sector privado se comprometan y participen de manera voluntaria. Esto es posible, por ejemplo, en el marco de la legislación fiscal o a través de prácticas de adjudicación para contratos públicos.</p>
    <h2 class="subtitle">Recomendaciones para los actores de la sociedad civil</h2>
    <p><span class="subitem">Establecer y desarrollar plataformas de concientización y transferencia de conocimiento y tecnología.</span> Debido a la a menudo deficiente formación (profesional), muchos conceptos básicos y herramientas para la gestión empresarial responsable son poco conocidos en América Latina. Esto aplica en mayor medida en regiones rurales periféricas. Para cambiar esta realidad, es necesario crear y desarrollar plataformas de concientización y transferencia de conocimiento y tecnología. Debieran realizarse a través de las cámaras de comercio (bilaterales), asociaciones empresariales, universidades, fundaciones y think tanks.</p>
    <p><span class="subitem">Acompañar las actividades de las empresas de manera constructiva y crítica, en el contexto de las iniciativas Multi-Stakeholder.</span> En las iniciativas Multi-Stakeholder cooperan organizaciones no gubernamentales, sindicatos, instituciones públicas y empresas. Aunque las empresas que participan en estas iniciativas no son inmunes a infracciones respecto a estándares sociales y / o ambientales en su cadena de valor, sin embargo, en comparación con las que no participan, las empresas miembros de tales iniciativas suelen tener mejores herramientas para detectar y sancionar estas infracciones. Además, la membresía generalmente indica un serio interés de la compañía en abordar los desafíos de manera abierta y transparente. Esto requiere de un apoyo constructivo y crítico de la sociedad civil organizada.</p>
    <p><span class="subitem">Abordar la gestión corporativa responsable en la formación.</span> Para impulsar la toma de conciencia y la competencia para abordar la gestión empresarial responsable en América Latina, se requiere de un mayor anclaje de los principios y valores éticos en la educación, desde la primera infancia hasta la educación universitaria.</p>
  </div>
</template>