<template>
  <div>
    <h2 class="subtitle">Recommendations for action for companies</h2>
    <p><span class="subitem">Formulate a clear and stringent corporate policy and anchor responsible management in the core processes.</span> A clear and stringent corporate policy is necessary in order to do business in a challenging environment such as Latin America in a sustainably responsible manner. Corporate management must make it credibly clear that it will only tolerate and reward responsible conduct, even if it results in short-term economic disadvantages for the company. In addition, companies should base all their business processes on and align them with the principles of responsible mangement. This enables them to follow the successful examples of companies that have recognized and use responsible management as a differentiating feature, innovation and productivity driver.</p>
    <p><span class="subitem">Ensure responsible corporate management in the value chain.</span> In addition to ensuring responsible conduct in the company's own activities, companies must also ensure that responsible corporate governance is practiced throughout the value chain, including subcontractors. To this end, companies must use their position in their respective spheres of influence and enter into an open and transparent dialogue with their business partners in order to jointly work out how responsible corporate management can be used as a differentiator, innovation and productivity driver.</p>
    <p><span class="subitem">Proactively contribute to the dissemination of the principles of responsible mangement.</span> In Latin America, responsible management is still a relatively uncommon concept. At the international level, stakeholders are increasingly expecting companies to behave responsibly worldwide and along the entire value chain. If in some countries, only low legal standards exist to protect environmental and social interests and their implementation is insufficiently monitored by state institutions, this can lead to competitive disadvantages for companies that come from countries with higher standards. To ensure a level playing field, (multinational) companies must proactively promote the principles of responsible management within their sphere of influence. This can be done, for example, through collective action approaches.</p>
    <h2 class="subtitle">Recommendations for actions for state actors</h2>
    <p><span class="subitem">Transfer good practices from the private sector to the public sector.</span> Over the past few years, many private companies have made great efforts to prevent, detect and, if necessary, sanction irresponsible behavior within the company. Numerous instruments developed in the private sector to ensure responsible behavior in organizations (code of conduct, ombudsperson, reporting office, etc.) can be adapted for the public sector. Thus, the three-step “prevent - uncover – sanction” tool should increasingly find its way into state institutions and state enterprises.</p>
    <p><span class="subitem">Adopt the pillar concept of the UN Guiding Principles for other areas.</span> The UN Guiding Principles for Business and Human Rights provide an important frame of reference that can also be applied to other areas of responsible management. On the one hand, the Guiding Principles define the duty of states to protect human rights against threats from private sector actors. On the other hand, they emphasize the obligation of companies to respect human rights. In addition, they enshrine the right to compensation in the event of human rights violations suffered by private sector actors.</p>
    <p><span class="subitem">Create incentives for the implementation of responsible management.</span> Companies are primarily responsible for implementing responsible management. This is particularly the case when companies voluntarily commit themselves to social and/or ecological concerns in addition to the existing legal requirements. The task of state institutions is to have effective control and sanction instruments at their disposal to detect and punish illegal conduct. In addition, the state should provide positive incentives for private sector actors to engage voluntarily. This can be done, for example, within the framework of tax legislation or public procurement practice.</p>
    <h2 class="subtitle">Recommendations for action for civil society actors</h2>
    <p><span class="subitem">Establish and further develop platforms for sensitization as well as for knowledge and technology transfer.</span> Due to the often inadequate (vocational) training, many basic concepts and instruments for responsible management are little known in Latin America. This applies increasingly to peripheral, rural regions. To change this, awareness-raising platforms and knowledge and technology transfer platforms need to be created and developed. This should be done under the auspices of (bilateral) chambers of commerce, business associations, universities, foundations and think tanks.</p>
    <p><span class="subitem">Within the framework of multi-stakeholder initiatives, accompany the activities of companies constructively and critically.</span> Non-governmental organizations, trade unions, public institutions and companies work together in multi-stakeholder initiatives. Even companies that participate in multi-stakeholder initiatives are not immune from violating social and/or ecological standards in their value chain. However, compared to non-members, member companies of such initiatives usually have better tools to detect and sanction violations. In addition, membership usually indicates a serious interest on the part of the company in addressing and tackling existing challenges openly and transparently. This requires constructive and critical support from organized civil society.</p>
    <p><span class="subitem">Address the issue of responsible corporate management in training.</span> In order to promote awareness and action competence for the issues of responsible management in Latin America, the examination of ethical principles and values must be anchored even more strongly in training, starting with early childhood education through to university education.</p>
  </div>
</template>