<template>
  <div>
    <p>
      Companies are repeatedly accused of violating social and/or ecological standards. Based on figures from the Business & Human Rights Resource Centre, German companies rank 5th worldwide in terms of the number of allegations of human rights violations made against them. Companies based in Switzerland rank 9th, Mexican companies 18th and Brazilian companies 19th (Kamminga 2015). The activities for the production and marketing of products and services are increasingly distributed worldwide. Companies are also active in countries within which minimal legal standards exist to protect ecological and social interests or whose implementation is inadequately monitored by state institutions. For this reason, companies are accorded great importance in terms of compliance with standards at all stages of the value chain. In view of the rising expectations of stakeholders (see e.g. Group Responsibility Initiative in Switzerland), responsible management is becoming increasingly important in an international context, also from a business perspective.
    </p>
    <p>
      Over the past few years, numerous international frameworks have been created to help companies align their responsible actions. These include, for example, the OECD Guidelines for Multinational Enterprises, the UN Global Compact, the UN Guiding Principles for Business and Human Rights, the UN Sustainable Development Goals (SDG), the ISO 26000 guideline and the Global Reporting Initiative. The aim of these frameworks is to support companies in making a positive contribution to global economic, ecological and social progress and in exploiting the economic advantages associated with responsible corporate action. In addition to general principles for responsible action in an international context, the frameworks cover specific areas of action. These include, in particular, human rights and working conditions, the environment, and the fight against bribery and corruption.
    </p>
    <p>
      Over the past few years, numerous international frameworks have been created to help companies align their responsible actions. These include, for example, the OECD Guidelines for Multinational Enterprises, the UN Global Compact, the UN Guiding Principles for Business and Human Rights, the UN Sustainable Development Goals (SDG), the ISO 26000 guideline and the Global Reporting Initiative. The aim of these frameworks is to support companies in making a positive contribution to global economic, ecological and social progress and in exploiting the economic advantages associated with responsible corporate action. In addition to general principles for responsible action in an international context, the frameworks cover specific areas of action. These include, in particular, human rights and working conditions, the environment, and the fight against bribery and corruption. In recent years, many international actors have become aware that the development policy objectives formulated in the United Nations’ Sustainable Development Goals can only be achieved with the active participation of the private sector. Entrepreneurship is an important component of an efficient economic system and an important driving force for sustainable economic, social and ecological development. International private sector involvement, e.g. in the form of foreign trade and direct investment, is also often associated with significant development policy impulses, for example through job creation, the improvement of infrastructure or the transfer of knowledge and technology. However, the beneficial effect of business activity is neither automatic nor distributed evenly across all population groups. In order to be able to use the advantages of business activities for sustainable social and economic development, the concept of responsible management is becoming increasingly important from a development policy perspective. In this context, it should be noted that many actors in Latin America believe that there is no such thing as responsible management. On the contrary, private enterprise activity is generally regarded as a “capitalist yield”, which applies particularly to the activities of multinational enterprises. At the same time, it is evident that there is currently still little scientific-based evidence on the implementation of responsible management in Latin America.
    </p>
    <p>
      Against this background, this multimedia work aims to use selected examples to describe the challenges facing companies in Latin America in the fields of human rights/working conditions, the environment and anti-corruption. In addition, short case studies will be used to illustrate how companies are actually implementing responsible management in these three areas. To achieve these goals, 128 company representatives and experts were interviewed in Argentina, Brazil, Colombia, Mexico and Peru between July and November 2017. These five countries account for 72% of Latin America's population and 74% of the region’s gross domestic product. Furthermore, these five countries account for about two thirds of both total Latin American imports and exports (65%), and account for nearly three quarters of all foreign direct investment made in the region (74%). In addition, 13 presentations were held in these countries, where representatives from politics, administration, business, science and civil society were given up-to-date information on specific aspects of responsible management. The lectures were held in cooperation with network partners such as bilateral chambers of commerce, universities and the Konrad Adenauer Foundation. In addition, five events on topics relating to responsible management were attended.
    </p>
    <p>
      Based on the findings generated, recommendations for action were formulated for (economic policy) decision-makers, company representatives and civil society actors from both Latin America and the German-speaking world. The multimedia work is structured in such a way that it can be read both in a linear sequence and in a non-linear order chosen by the reader. On the one hand, the content can be accessed via the countries and, on the other hand, via the areas of action of responsible management. In addition, the research diary and map offer the opportunity to get closer to the contents.
    </p>
  </div>
</template>