[[redirects]]
  from = "https://csr-la.netlify.com"
  to = "https://csr-la.net"
  status = 301
  force = true

[[redirects]]
  from = "/de"
  to = "/en"
  status = 302
  force = false
  conditions = {Language = ["de"]}