[[redirects]]
  from = "https://csr-la.netlify.com"
  to = "https://csr-la.net"
  status = 301
  force = true

[[redirects]]
  from = "/de/*"
  to = "/en/:splat"
  status = 302
  force = true
  conditions = {Language = ["de"]}