import Vue from "vue";
import IconBase from "@/components/common/IconBase";
import IconMenu from "@/components/icons/IconMenu";
import IconAltitude from "@/components/icons/IconAltitude";
import IconMoney from "@/components/icons/IconMoney";
import IconUserGroup from "@/components/icons/IconUserGroup";
import IconArrowLeft from "@/components/icons/IconArrowLeft";
import IconArrowRight from "@/components/icons/IconArrowRight";
import IconBook from "@/components/icons/IconBook";
import IconCheveronRight from "@/components/icons/IconCheveronRight";
import IconCheveronLeft from "@/components/icons/IconCheveronLeft";
import IconCheveronDown from "@/components/icons/IconCheveronDown";
import IconCheveronDownCircle from "@/components/icons/IconCheveronDownCircle";
import IconCheveronUp from "@/components/icons/IconCheveronUp";
import IconPlay from "@/components/icons/IconPlay";
import IconClose from "@/components/icons/IconClose";
import IconGlobe from "@/components/icons/IconGlobe";
import IconInformation from "@/components/icons/IconInformation";
import IconAddCircle from "@/components/icons/IconAddCircle";
import IconRemoveCircle from "@/components/icons/IconRemoveCircle";
import IconPlane from "@/components/icons/IconPlane";
import IconTaxi from "@/components/icons/IconTaxi";
import IconInterview from "@/components/icons/IconInterview";
import IconMexico from "@/components/icons/IconMexico";
import IconPeru from "@/components/icons/IconPeru";
import IconColombia from "@/components/icons/IconColombia";
import IconBrazil from "@/components/icons/IconBrazil";
import IconArgentina from "@/components/icons/IconArgentina";
import SideTable from "@/components/SideTable";
import ImageSlider from "@/components/ImageSlider";
import VideoCard from "@/components/VideoCard";
import PageNavBtn from "@/components/common/PageNavBtn";
import FloatingMenu from "@/components/common/FloatingMenu";

Vue.component("IconBase", IconBase);
Vue.component("IconMenu", IconMenu);
Vue.component("IconAltitude", IconAltitude);
Vue.component("IconMoney", IconMoney);
Vue.component("IconUserGroup", IconUserGroup);
Vue.component("IconArrowLeft", IconArrowLeft);
Vue.component("IconArrowRight", IconArrowRight);
Vue.component("IconBook", IconBook);
Vue.component("IconCheveronRight", IconCheveronRight);
Vue.component("IconCheveronLeft", IconCheveronLeft);
Vue.component("IconCheveronDown", IconCheveronDown);
Vue.component("IconCheveronDownCircle", IconCheveronDownCircle);
Vue.component("IconCheveronUp", IconCheveronUp);
Vue.component("IconPlay", IconPlay);
Vue.component("IconClose", IconClose);
Vue.component("IconGlobe", IconGlobe);
Vue.component("IconInformation", IconInformation);
Vue.component("IconAddCircle", IconAddCircle);
Vue.component("IconRemoveCircle", IconRemoveCircle);
Vue.component("IconPlane", IconPlane);
Vue.component("IconTaxi", IconTaxi);
Vue.component("IconInterview", IconInterview);
Vue.component("IconMexico", IconMexico);
Vue.component("IconPeru", IconPeru);
Vue.component("IconColombia", IconColombia);
Vue.component("IconBrazil", IconBrazil);
Vue.component("IconArgentina", IconArgentina);
Vue.component("SideTable", SideTable);
Vue.component("ImageSlider", ImageSlider);
Vue.component("VideoCard", VideoCard);
Vue.component("PageNavBtn", PageNavBtn);
Vue.component("FloatingMenu", FloatingMenu);
