<template>
  <div>
    <h2 class="subtitle">Handlungsempfehlungen für Unternehmen</h2>
    <p><span class="subitem">Klare und stringente Unternehmenspolitik formulieren und ver&shy;ant&shy;wor&shy;tungs&shy;volle Unternehmensführung in den Kernprozessen verankern.</span> Um in einem herausfordernden Umfeld wie Lateinamerika nachhaltig verantwortungsvoll Geschäfte zu machen, ist eine klare und stringente Unternehmenspolitik notwendig. Die Unternehmensleitung muss glaubhaft deutlich machen, dass sie nur ver&shy;ant&shy;wor&shy;tungs&shy;volles Handeln toleriert und honoriert, auch wenn das Unternehmen dadurch kurzfristig wirtschaftliche Nachteile erleidet. Darüber hinaus sollten Unternehmen sämtliche Geschäftsprozesse von den Prinzipien der verantwortungsvollen Unternehmensführung her denken und darauf ausrichten. Damit können sie den erfolgreichen Beispielen von Unternehmen folgen, die verantwortungsvolle Unternehmensführung als Differenzierungsmerkmal, Innovations- und Produktivitätstreiber erkannt haben und nutzen.</p>
    <p><span class="subitem">Verantwortungsvolle Unternehmensführung in der Wertschöpfungskette sicherstellen.</span> Neben der Gewährleistung des verantwortungsvollen Handelns bei den unternehmenseigenen Aktivitäten müssen die Unternehmen auch dafür Sorge tragen, dass verantwortungsvolle Unternehmensführung in der gesamten Wertschöpfungskette gelebt wird, inklusive der Sublieferanten. Hierfür müssen die Unternehmen ihre Stellung in ihrer jeweiligen Einflusssphäre nutzen und mit ihren Geschäftspartnern in einen offenen und transparenten Dialog treten, um gemeinsam zu erarbeiten, wie die verantwortungsvolle Unternehmensführung als Differenzierungsmerkmal, Innovations- und Produktivitätstreiber genutzt werden kann.</p>
    <p><span class="subitem">Proaktiv an der Verbreitung der Prinzipien verantwortungsvoller Un&shy;ter&shy;neh&shy;mens&shy;füh&shy;rung mitwirken.</span> In Lateinamerika ist die verantwortungsvolle Unternehmensführung ein noch vergleichsweise wenig verbreitetes Konzept. International steigen die Erwartungen der Anspruchsgruppen an Unternehmen, sich weltweit und entlang der gesamten Wertschöpfungskette verantwortungsvoll zu verhalten. Wenn in einigen Ländern lediglich geringe gesetzliche Standards zum Schutz ökologischer und gesellschaftlicher Belange existieren oder deren Umsetzung nur unzureichend durch die staatlichen Institutionen überprüft wird, kann dies zu Wettbewerbsnachteilen für Unternehmen führen, die aus Ländern kommen, in denen höhere Ansprüche herrschen. Um einheitliche Wettbewerbsbedingungen sicherzustellen, müssen sich (multinationale) Unternehmen innerhalb ihrer Einflusssphäre proaktiv für die Verbreitung der Prinzipien der ver&shy;ant&shy;wor&shy;tungs&shy;vollen Unternehmensführung einsetzen. Dies kann z.B. im Rahmen von Collective Action Ansätzen geschehen.</p>
    <h2 class="subtitle">Handlungsempfehlungen für staatliche Akteure</h2>
    <p><span class="subitem">Good Practices aus dem Privatsektor in den öffentlichen Sektor übertragen.</span> In den zurückliegenden Jahren haben zahlreiche privatwirtschaftliche Unternehmen große Anstrengungen unternommen, um unverantwortlichem Handeln unternehmensintern vorzubeugen, dieses aufzudecken und wenn nötig zu sanktionieren. Zahlreiche Instrumente, die im privaten Sektor entwickelt wurden, um verantwortungsvolles Handeln in Organisationen sicherzustellen (Ver&shy;hal&shy;tens&shy;ko&shy;dex, Ombudsperson, Meldestelle etc.), lassen sich für den öffentlichen Sektor adaptieren. So sollte der Dreischritt „vorbeugen – aufdecken – sanktionieren“ vermehrt auch in staatlichen Institutionen und Staatsunternehmen Einzug halten.</p>
    <p><span class="subitem">Säulenkonzept der UN-Leitprinzipien für andere Themengebiete übernehmen.</span> Die UN-Leitprinzipien für Wirtschaft und Menschenrechte liefern einen wichtigen Bezugsrahmen, der sich auch auf andere Themengebiete der verantwortungsvollen Unternehmensführung übertragen lässt. Zum einen definieren die Leitprinzipien die Pflicht der Staaten, die Menschenrechte auch gegenüber Bedrohungen durch privatwirtschaftliche Akteure zu schützen. Zum anderen betonen sie die Pflicht der Unternehmen, die Menschenrechte zu respektieren. Darüber hinaus verankern sie ein Recht auf Wiedergutmachung im Falle erlittener Menschenrechtsverletzungen durch privatwirtschaftliche Akteure.</p>
    <p><span class="subitem">Anreize zur Umsetzung verantwortungsvoller Unternehmensführung schaffen.</span> Für die Umsetzung verantwortungsvoller Unternehmensführung sind in erster Linie die Unternehmen verantwortlich. Dies gilt besonders dann, wenn sich die Unternehmen über die bestehenden gesetzlichen Bestimmungen hinaus zusätzlich und freiwillig für gesellschaftliche und/oder ökologische Belange einsetzen. Die Aufgabe der staatlichen Institutionen ist es, über wirkungsvolle Kontroll- und Sanktionsinstrumente zu verfügen, um rechtswidriges Verhalten aufzudecken und zu ahnden. Daneben sollte der Staat positive Anreize setzen, damit sich die privatwirtschaftlichen Akteure freiwillig engagieren. Dies kann bspw. im Rahmen der Steuergesetzgebung oder der Vergabepraxis für öffentliche Aufträge erfolgen.</p>
    <h2 class="subtitle">Handlungsempfehlungen für zivilgesellschaftliche Akteure</h2>
    <p><span class="subitem">Plattformen zur Sensibilisierung sowie zum Wissens- und Technologie-Transfer etablieren und weiterentwickeln.</span> Aufgrund der häufig unzureichenden (beruflichen) Ausbildung, sind in Lateinamerika viele grundlegende Konzepte und Instrumente zur verantwortungsvollen Unternehmensführung wenig bekannt. Dies gilt in gesteigertem Maße für die peripheren, ländlichen Regionen. Um dies zu ändern, müssen Plattformen zur Sensibilisierung sowie zum Wissens- und Technologie-Transfer geschaffen und weiterentwickelt werden. Dies sollte in Trägerschaft von (bilateralen) Handelskammern, Wirtschaftsverbänden, Hochschulen, Stiftungen und Think-tanks geschehen.</p>
    <p><span class="subitem">Im Rahmen von Multi-Stakeholder-Initiativen die Aktivitäten der Unternehmen konstruktiv-kritisch begleiten.</span> In Multi-Stakeholder-Initiativen arbeiten Nichtregierungsorganisation, Gewerkschaften, öffentliche Institutionen und Unternehmen zusammen. Zwar sind auch Unternehmen, die sich an Multi-Stakeholder-Initiativen beteiligen, nicht davor gefeit, dass in ihrer Wert&shy;schöp&shy;fungs&shy;ket&shy;te gegen soziale und/oder ökologische Standards verstoßen wird. Verglichen mit Nichtmitgliedern haben Mitgliedsunternehmen solcher Initiativen jedoch in der Regel bessere Instrumente, um Verstöße aufzudecken und zu sanktionieren. Außerdem deutet die Mitgliedschaft in der Regel auf ein ernsthaftes Interesse des Unternehmens hin, die bestehenden Herausforderungen offen und transparent anzusprechen und anzugehen. Hierzu bedarf es der konstruktiv-kritischen Begleitung durch die organisierte Zivilgesellschaft.</p>
    <p><span class="subitem">Verantwortungsvolle Unternehmensführung in der Ausbildung the&shy;ma&shy;ti&shy;sie&shy;ren.</span> Um in Lateinamerika Bewusstsein und Handlungskompetenz für die Themen der verantwortungsvollen Unternehmensführung zu fördern, muss die Auseinandersetzung mit ethischen Prinzipien und Werten noch stärker in der Ausbildung verankert werden, angefangen bei der frühkindlichen Erziehung bis hin zur universitären Bildung.</p>
  </div>
</template>