<template>
  <div>
    <h2 class="subtitle">Recomendações de ações para empresas</h2>
    <p><span class="subitem">Formular políticas empresariais claras e rigorosas e integrar a gestão responsável empresarial nos processos do negócio.</span> Para poder fazer negócios num ambiente complexo como o da América Latina, é preciso uma política empresarial clara e rigorosa. A direção da empresa deve deixar claro, de forma crível, que só aceita e apoia ações responsáveis, mesmo que possam representar desvantagens econômicas de curto prazo. Além disso, as empresas devem pensar e alinhar todos os processos de negócios referentes aos princípios da gestão responsável de empresas. Assim, podem seguir os exemplos de sucesso de empresas que reconheceram e usam a gestão responsável como caraterística diferenciadora e motor de inovação e produtividade.</p>
    <p><span class="subitem">Inserir a gestão responsável empresarial na cadeia de valor.</span> Além de garantir a ação responsável nas atividades próprias da empresa, a companhia também deve assegurar que a gestão responsável empresarial seja vivida também em toda a cadeia de valor, incluindo os terceirizados. Para isso, as empresas devem aproveitar sua posição e sua respectiva esfera de influência e estabelecer um diálogo aberto e transparente com seus parceiros, para desenvolverem juntos uma gestão responsável empresarial como caraterística diferenciadora e motor de inovação e produtividade.</p>
    <p><span class="subitem">Cooperar de forma proativa na divulgação dos princípios da gestão responsável empresarial.</span> Na América Latina, a gestão responsável empresarial ainda é relativamente pouco divulgada. Internacionalmente, as partes interessadas aumentam a pressão sobre as empresas para que se comportem de forma responsável na cadeia de valor e em nível mundial. Se alguns países tiverem leis fracas de proteção do meio ambiente e da sociedade ou se a fiscalização por parte das instituições estatais for insuficiente, podem-se produzir desvantagens competitivas para empresas procedentes de países com exigências mais rígidas. Para garantir condições competitivas uniformes, as empresas (multinacionais) devem promover ativamente na sua esfera de influência a divulgação dos princípios da gestão responsável empresarial. Isso também pode ser feito, por exemplo, no marco de abordagens do tipo ação coletiva.</p>
    <h2 class="subtitle">Recomendações de ação para atores estatais</h2>
    <p><span class="subitem">Transferir boas práticas de setor privado ao setor público.</span> Nos últimos anos, muitas empresas privadas realizaram grandes esforços para prevenir as ações irresponsáveis, assumir os casos e, caso necessário, sancioná-las. Muitos instrumentos criados no setor privado para garantir a ação responsável nas organizações (código de conduta, ouvidorias, departamentos de queixas, etc.), podem ser adaptados ao setor público. Por exemplo, a tríade “prevenir, revelar e sancionar”, deveria ser mais implementada em instituições e empresas públicas.</p>
    <p><span class="subitem">Implementar o conceito dos pilares das Nações Unidas para outras áreas temáticas.</span> Os princípios orientadores das Nações Unidas para empresas e direitos humanos estabelecem um marco referencial importante, transferível a outras áreas temáticas da gestão responsável empresarial. Por um lado, os princípios orientadores definem a obrigação dos Estados de proteger os direitos humanos também contra ameaças proferidas por atores do setor privado. Por outro lado, destacam a obrigação das empresas de respeitar os direitos humanos. Além disso, instalam o direito de indenização em caso de violações dos direitos humanos sofridas por atores do setor privado.</p>
    <p><span class="subitem">Criar incentivos para a implementação da gestão responsável empresarial.</span> Em primeiro lugar, os responsáveis pela gestão responsável empresarial são as companhias. Especialmente quando as empresas, além das disposições legais existentes e em forma voluntária, defendem interesses sociais e/ou ambientais. A tarefa das instituições estatais é dispor de instrumentos de controle e sanção eficazes para poder detectar e punir comportamentos ilegais. Além disso, o estado deve criar incentivos positivos para fomentar a ação voluntária dos atores do setor privado. Isso pode ocorrer, por exemplo, no marco da legislação tributária ou da prática de obtenção de contratos públicos.</p>
    <h2 class="subtitle">Recomendações de ações para a sociedade civil</h2>
    <p><span class="subitem">Plataformas para a sensibilização e a transferência de conhecimentos e tecnologias.</span> Devido à formação (profissional) com frequência insuficiente, na América Latina muitos conceitos e instrumentos da gestão responsável empresarial são pouco conhecidos. Isso ocorre ainda mais nas regiões periféricas e rurais. Para modificar isso, devem-se criar e aperfeiçoar plataformas para a transferência de conhecimentos e tecnologias. Estas iniciativas deviam estar nas mãos de câmaras de comércio (binacionais), associações econômicas, universidades, fundações e think-tanks.</p>
    <p><span class="subitem">Acompanhar criticamente as atividades das empresas no marco de iniciativas das partes interessadas.</span> Nas iniciativas das partes interessadas, cooperam organizações não-governamentais, sindicatos, instituições públicas e empresas. As empresas que participam das iniciativas das partes interessadas não são imunes contra violações das normas sociais ou do meio ambiente, mas, comparado com os não-membros, essas empresas dispõem de melhores instrumentos para expor e sancionar as violações. Além disso, a participação indica também um interesse genuíno da empresa de abordar e resolver os desafios existentes em forma aberta e transparente. Para isso é preciso o acompanhamento crítico da sociedade civil organizada.</p>
    <p><span class="subitem">Abordar o tema da gestão responsável na formação profissional.</span> Para fomentar a consciência e a competência referente aos temas da gestão responsável empresarial na América Latina, deve se estimular ainda mais o debate sobre os princípios e valores éticos no processo de formação, começando com a educação precoce até a formação acadêmica.</p>
  </div>
</template>